#!/bin/bash
#
# (C) Copyright 2011-2012 Sergey A. Babkin.
# This file is a part of Triceps.
# See the file COPYRIGHT for the copyright notice and license information
#
#
# Building of a release package.

PRODUCT=triceps
INFO=`svn info .` || exit 1
URL=`echo "$INFO" | sed -n 's/^URL: //p'`
[ -n "$URL" ] || { echo "Could not find SVN URL" >&2; exit 1; }
VERSION=`basename "$URL"`

DIR="$PRODUCT-$VERSION"
[ -r "$DIR" ] && {
	rm -rf "$DIR" || exit 1
}

svn export "$URL" "$DIR" || exit 1
echo
echo "Building the documentation..."
rm -rf "$DIR/doc/blog" || exit 1
# This is my directory with docbook tools, to avoid downnloading them into the release.
export TRICEPS_TOOLS_BASE=$HOME/arch/docbook
if [ ! -d "$TRICEPS_TOOLS_BASE" ]; then {
	TRICEPS_TOOLS_BASE=
	make -C "$DIR/doc/dbtools" all || exit 1
} fi
make -C "$DIR/doc/src" all || exit 1
make -C "$DIR/doc/src" cleanwork || exit 1

tar czvf "$DIR.tgz" "$DIR" || exit 1

echo
echo "Building the exported code to make sure..."
make -C "$DIR" all test || exit 1
