FILES=index.html

all:

# To create a shell:
# ssh -t babkin,triceps@shell.sf.net create
#
# The web.sf.net allows to skip the VM creation.
# scp $(FILES) babkin,triceps@shell.sf.net:/home/project-web/triceps/htdocs/
upload:
	scp $(FILES) babkin,triceps@web.sf.net:/home/project-web/triceps/htdocs/
